---
- name: Pre , Post tasks and Tags example
  hosts: localhost
  become: true
  tags:
     - rit
  pre_tasks:
  - debug: msg="Started task with tag" - rit.
  tasks:
   - name: Going to execute the main task
     debug: msg="Currently in the target server"
  post_tasks:
  - debug: msg="Completed task with tag" - rit.
  - name: Play without tags
    hosts: localhost
    become: true
    tasks:
    - name: Command to list files
      shell: ls -lrt > niranjan.txt
